name: Build Android APK

  on:
    push:
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-release
          path: app/build/outputs/apk/release/app-release.apk
